name: CI Pipeline

on:
push:
branches: [ main, login-api ]
pull_request:
branches: [ main ]

jobs:
build:
runs-on: ubuntu-latest


steps:
  - name: Checkout Code
    uses: actions/checkout@v3

  - name: Setup Node
    uses: actions/setup-node@v3
    with:
      node-version: 18

  - name: Install Dependencies
    run: npm install

  - name: Run Lint
    run: npm run lint || echo "No lint configured"

  - name: Security Scan
    run: npm audit --audit-level=high || true

  - name: Run Tests
    run: npm test || echo "No tests configured"
s
